export const quizzes = [
  {
    topic: "Foundations",
    difficulty: "Medium",
    question: "What is software engineering primarily concerned with?",
    options: ["Writing code only", "All aspects of software production", "Hardware development", "Network installation"],
    answer: "B",
    explanation: "Software engineering covers the entire lifecycle—from specification to maintenance, not just coding.",
  },
  {
    topic: "Foundations",
    difficulty: "Medium",
    question: "Why did software engineering emerge as a discipline?",
    options: ["Hardware shortage", "Software crisis", "Internet growth", "Programming languages"],
    answer: "B",
    explanation: "The “software crisis” involved late delivery, high cost, and unreliable systems, which led to the need for structured engineering approaches.",
  },
  {
    topic: "Foundations",
    difficulty: "Medium",
    question: "Software systems are described as:",
    options: ["Physical", "Mechanical", "Abstract and intangible", "Static"],
    answer: "C",
    explanation: "Software is not constrained by physical laws, making it flexible but highly complex.",
  },
  {
    topic: "Foundations",
    difficulty: "Medium",
    question: "What is a major challenge of software systems?",
    options: ["Weight", "Power consumption", "Complexity", "Temperature"],
    answer: "C",
    explanation: "Because software has no physical limits, it can grow extremely complex and difficult to manage.",
  },
  {
    topic: "Foundations",
    difficulty: "Medium",
    question: "Professional software is typically developed by:",
    options: ["Individuals only", "Teams", "Machines", "Customers"],
    answer: "B",
    explanation: "Large systems require collaboration, coordination, and maintenance, hence teams are needed.  🔹",
  },
  {
    topic: "Software Products",
    difficulty: "Medium",
    question: "What is a software product?",
    options: ["Hardware tool", "System with useful functionality", "Network device", "Programming language"],
    answer: "B",
    explanation: "Software products provide useful functionality to customers, e.g., Excel, mobile apps.",
  },
  {
    topic: "Software Products",
    difficulty: "Medium",
    question: "Generic software is developed for:",
    options: ["One client", "Many users", "Developers only", "Government only"],
    answer: "B",
    explanation: "Generic software targets a wide range of customers (e.g., Microsoft Word).",
  },
  {
    topic: "Software Products",
    difficulty: "Medium",
    question: "Custom software is developed for:",
    options: ["Multiple companies", "A specific client", "Everyone", "Open source"],
    answer: "B",
    explanation: "Custom software is tailored to specific business needs.",
  },
  {
    topic: "Software Products",
    difficulty: "Medium",
    question: "Product development starts with:",
    options: ["Coding", "Product vision", "Testing", "Deployment"],
    answer: "B",
    explanation: "A product vision defines what to build, for whom, and why.",
  },
  {
    topic: "Software Products",
    difficulty: "Medium",
    question: "Product vision answers which question?",
    options: ["How to code", "Who are the users", "Which language to use", "Where to host"],
    answer: "B",
    explanation: "Vision defines target users, purpose, and value.  🔹",
  },
  {
    topic: "Product Management",
    difficulty: "Medium",
    question: "Who is responsible for a software product?",
    options: ["Tester", "Product manager", "Programmer", "Designer"],
    answer: "B",
    explanation: "The product manager oversees planning, development, and customer alignment.",
  },
  {
    topic: "Product Management",
    difficulty: "Medium",
    question: "Product managers focus on:",
    options: ["Code only", "Customers and business needs", "Hardware", "Testing only"],
    answer: "B",
    explanation: "They act as a bridge between business, users, and developers.",
  },
  {
    topic: "Product Management",
    difficulty: "Medium",
    question: "Product backlog is:",
    options: ["Code repository", "To-do list of features", "Database", "UI design"],
    answer: "B",
    explanation: "Backlog contains prioritized work items like features and improvements.",
  },
  {
    topic: "Product Management",
    difficulty: "Medium",
    question: "Acceptance testing ensures:",
    options: ["Code compiles", "Product meets goals", "UI is beautiful", "Database is full"],
    answer: "B",
    explanation: "It checks whether the product satisfies user needs and expectations.",
  },
  {
    topic: "Product Management",
    difficulty: "Medium",
    question: "Prototyping is used to:",
    options: ["Finalize system", "Explore ideas", "Deployment system", "Remove features"],
    answer: "B",
    explanation: "Prototypes help test ideas and user reactions early.  🔹",
  },
  {
    topic: "Agile",
    difficulty: "Medium",
    question: "Agile focuses on:",
    options: ["Documentation", "Flexibility and speed", "Hardware", "Cost only"],
    answer: "B",
    explanation: "Agile emphasizes rapid delivery and adaptability to change.",
  },
  {
    topic: "Agile",
    difficulty: "Medium",
    question: "Agile development is based on:",
    options: ["Linear process", "Incremental development", "Waterfall", "Hardware cycles"],
    answer: "B",
    explanation: "Software is built in small increments with feedback loops.",
  },
  {
    topic: "Agile",
    difficulty: "Medium",
    question: "Agile values:",
    options: ["Contracts over collaboration", "Documentation over software", "Working software over documentation", "Plans over change"],
    answer: "C",
    explanation: "Agile prioritizes working software.",
  },
  {
    topic: "Agile",
    difficulty: "Medium",
    question: "Agile supports:",
    options: ["Fixed requirements", "Changing requirements", "No requirements", "Hardware"],
    answer: "B",
    explanation: "Change is expected and embraced.",
  },
  {
    topic: "Agile",
    difficulty: "Medium",
    question: "Incremental delivery means:",
    options: ["Deliver everything at once", "Deliver in parts", "No delivery", "Testing only"],
    answer: "B",
    explanation: "Software is delivered in usable increments.  🔹",
  },
  {
    topic: "XP",
    difficulty: "Medium",
    question: "XP stands for:",
    options: ["Extra Programming", "Extreme Programming", "Extended Processing", "Experimental Programming"],
    answer: "B",
    explanation: "XP is an Agile method emphasizing coding practices and rapid delivery.",
  },
  {
    topic: "XP",
    difficulty: "Medium",
    question: "XP promotes:",
    options: ["Documentation", "Pair programming", "Hardware", "Waterfall"],
    answer: "B",
    explanation: "Two developers work together to improve quality.",
  },
  {
    topic: "XP",
    difficulty: "Medium",
    question: "Test-driven development means:",
    options: ["Test after coding", "Test before coding", "No testing", "Manual testing only"],
    answer: "B",
    explanation: "Tests are written before code to define expected behavior.",
  },
  {
    topic: "XP",
    difficulty: "Medium",
    question: "Continuous integration ensures:",
    options: ["No testing", "Frequent integration", "One-time deployment", "Hardware checks"],
    answer: "B",
    explanation: "Code is integrated and tested frequently to avoid issues.",
  },
  {
    topic: "XP",
    difficulty: "Medium",
    question: "Refactoring means:",
    options: ["Adding features", "Improving code structure", "Deleting code", "Testing"],
    answer: "B",
    explanation: "Improves readability and maintainability.  🔹",
  },
  {
    topic: "Scrum",
    difficulty: "Medium",
    question: "Scrum is:",
    options: ["Programming language", "Agile framework", "Hardware tool", "Testing method"],
    answer: "B",
    explanation: "Scrum organizes Agile development into structured processes.",
  },
  {
    topic: "Scrum",
    difficulty: "Medium",
    question: "A sprint lasts:",
    options: ["1 year", "2\u20134 weeks", "1 day", "6 months"],
    answer: "B",
    explanation: "Short development cycle producing usable increments.",
  },
  {
    topic: "Scrum",
    difficulty: "Medium",
    question: "Product owner is responsible for:",
    options: ["Coding", "Features and priorities", "Testing", "UI"],
    answer: "B",
    explanation: "Defines and prioritizes product requirements.",
  },
  {
    topic: "Scrum",
    difficulty: "Medium",
    question: "ScrumMaster is:",
    options: ["Manager", "Coach", "Developer", "Tester"],
    answer: "B",
    explanation: "Guides team in using Scrum effectively.",
  },
  {
    topic: "Scrum",
    difficulty: "Medium",
    question: "Daily scrum is:",
    options: ["Weekly meeting", "Daily short meeting", "Monthly review", "Testing session"],
    answer: "B",
    explanation: "Used to track progress and plan work.  🔹",
  },
  {
    topic: "User Focus",
    difficulty: "Medium",
    question: "A feature is:",
    options: ["A bug", "Functionality", "UI only", "Code"],
    answer: "B",
    explanation: "Feature = fragment of functionality.",
  },
  {
    topic: "User Focus",
    difficulty: "Medium",
    question: "Personas represent:",
    options: ["Code", "Imagined users", "Features", "Tests"],
    answer: "B",
    explanation: "They help developers understand user needs.",
  },
  {
    topic: "User Focus",
    difficulty: "Medium",
    question: "Scenarios describe:",
    options: ["Code structure", "User interaction", "Hardware", "Testing"],
    answer: "B",
    explanation: "Scenarios show how users use the system.",
  },
  {
    topic: "User Focus",
    difficulty: "Medium",
    question: "Personas help developers:",
    options: ["Code faster", "Empathize with users", "Reduce cost", "Test"],
    answer: "B",
    explanation: "They allow developers to “step into user’s shoes”.",
  },
  {
    topic: "User Focus",
    difficulty: "Medium",
    question: "Scenario is NOT:",
    options: ["Narrative", "Specification", "Usage description", "User interaction"],
    answer: "B",
    explanation: "Scenarios are informal and not detailed specifications.  🔹",
  },
  {
    topic: "Project Management",
    difficulty: "Medium",
    question: "Product backlog contains:",
    options: ["Code", "Tasks", "UI", "Hardware"],
    answer: "B",
    explanation: "List of features, fixes, and improvements.",
  },
  {
    topic: "Project Management",
    difficulty: "Medium",
    question: "Backlog items are called:",
    options: ["Features", "PBIs", "Tasks", "Stories"],
    answer: "B",
    explanation: "Product Backlog Items (PBIs).",
  },
  {
    topic: "Project Management",
    difficulty: "Medium",
    question: "Story points measure:",
    options: ["Time", "Effort", "Code size", "Speed"],
    answer: "B",
    explanation: "They estimate relative effort and complexity.",
  },
  {
    topic: "Project Management",
    difficulty: "Medium",
    question: "Sprint goal defines:",
    options: ["Code", "Objective", "UI", "Testing"],
    answer: "B",
    explanation: "It sets what the sprint should achieve.",
  },
  {
    topic: "Project Management",
    difficulty: "Medium",
    question: "Sprint backlog is:",
    options: ["Product backlog", "Subset for sprint", "Code", "UI"],
    answer: "B",
    explanation: "It contains items selected for that sprint.  🔹",
  },
  {
    topic: "Scrum / Teams",
    difficulty: "Medium",
    question: "Ideal Scrum team size is:",
    options: ["1\u20132", "5\u20138", "20", "50"],
    answer: "B",
    explanation: "Small enough for communication, large enough for diversity.",
  },
  {
    topic: "Scrum / Teams",
    difficulty: "Medium",
    question: "Self-organizing team means:",
    options: ["No leader", "Team makes decisions", "Manager controls", "Fixed roles"],
    answer: "B",
    explanation: "Team members decide how to work collaboratively.",
  },
  {
    topic: "Scrum / Teams",
    difficulty: "Medium",
    question: "Scrum assumes teams are:",
    options: ["Remote", "Co-located", "Part-time", "Independent"],
    answer: "B",
    explanation: "Designed for close communication environments.",
  },
  {
    topic: "Scrum / Teams",
    difficulty: "Medium",
    question: "Continuous integration involves:",
    options: ["Manual testing", "Frequent merging", "Deployment only", "UI updates"],
    answer: "B",
    explanation: "The correct answer is B.",
  },
  {
    topic: "Scrum / Teams",
    difficulty: "Medium",
    question: "Test automation ensures:",
    options: ["No testing", "Faster testing", "Manual testing", "UI"],
    answer: "B",
    explanation: "The correct answer is B.",
  },
  {
    topic: "General Concepts",
    difficulty: "Medium",
    question: "Software evolution is:",
    options: ["Static process", "Continuous change", "Hardware change", "Coding"],
    answer: "B",
    explanation: "The correct answer is B.",
  },
  {
    topic: "General Concepts",
    difficulty: "Medium",
    question: "Software complexity arises due to:",
    options: ["Hardware", "Growth and changes", "UI", "Testing"],
    answer: "B",
    explanation: "The correct answer is B.",
  },
  {
    topic: "General Concepts",
    difficulty: "Medium",
    question: "Software engineering methods include:",
    options: ["Design only", "Techniques and processes", "Hardware", "Testing only"],
    answer: "B",
    explanation: "The correct answer is B.",
  },
  {
    topic: "General Concepts",
    difficulty: "Medium",
    question: "Software product line means:",
    options: ["One product", "Related products", "Hardware", "UI"],
    answer: "B",
    explanation: "The correct answer is B.",
  },
  {
    topic: "General Concepts",
    difficulty: "Medium",
    question: "Platform allows:",
    options: ["Coding", "Building applications", "Testing", "Deployment"],
    answer: "B",
    explanation: "Platforms provide base functionality for building new applications.",
  },
];
